//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class systemdbEntities : DbContext
    {
        public systemdbEntities()
            : base("name=systemdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<adminaccount> adminaccounts { get; set; }
        public virtual DbSet<bussinesstype> bussinesstypes { get; set; }
        public virtual DbSet<clientaccount> clientaccounts { get; set; }
        public virtual DbSet<listreward> listrewards { get; set; }
        public virtual DbSet<promotion> promotions { get; set; }
        public virtual DbSet<qrcode> qrcodes { get; set; }
        public virtual DbSet<reward> rewards { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<storeaccount> storeaccounts { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
    }
}
